spring:
  application:
    name: kms-api-application

kms:
  admin-access:
    header-name: X-Demo-Role-Code
    super-admin-role-code: PLATFORM_ADMIN

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
