create table if not exists roles (
  id bigint generated by default as identity primary key,
  code varchar(100) not null unique,
  display_name_nl varchar(255) not null,
  description_nl varchar(500) not null,
  scope_type varchar(50) not null,
  permission_level varchar(50) not null,
  system_role boolean not null default false,
  active boolean not null default true
);

create table if not exists capabilities (
  id bigint generated by default as identity primary key,
  code varchar(100) not null unique,
  display_name_nl varchar(255) not null,
  description_nl varchar(500) not null,
  active boolean not null default true
);

create table if not exists role_capability_codes (
  role_id bigint not null,
  capability_code varchar(100) not null,
  primary key (role_id, capability_code),
  constraint fk_role_capability_role
    foreign key (role_id) references roles(id)
);

create table if not exists user_assignments (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  role_code varchar(100) not null,
  scope_type varchar(50) not null,
  board_id bigint,
  school_id bigint,
  permission_level varchar(50) not null,
  active boolean not null default true,
  valid_from timestamp with time zone,
  valid_to timestamp with time zone
);

create table if not exists score_configurations (
  id bigint generated by default as identity primary key,
  code varchar(100) not null unique,
  numeric_value integer not null,
  display_label_nl varchar(255) not null,
  description_nl varchar(500) not null,
  sort_order integer not null,
  active boolean not null default true
);

create table if not exists inspection_domains (
  id bigint generated by default as identity primary key,
  code varchar(100) not null unique,
  display_name_nl varchar(255) not null,
  description_nl varchar(500) not null,
  sort_order integer not null,
  active boolean not null default true
);

create table if not exists inspection_topics (
  id bigint generated by default as identity primary key,
  domain_id bigint not null,
  code varchar(100) not null unique,
  display_name_nl varchar(255) not null,
  description_nl varchar(500) not null,
  sort_order integer not null,
  active boolean not null default true,
  constraint fk_inspection_topic_domain
    foreign key (domain_id) references inspection_domains(id)
);

create table if not exists document_type_definitions (
  id bigint generated by default as identity primary key,
  code varchar(100) not null unique,
  display_name_nl varchar(255) not null,
  description_nl varchar(500) not null,
  active boolean not null default true,
  required_for_onboarding boolean not null default false
);

create table if not exists audit_events (
  id bigint generated by default as identity primary key,
  action varchar(150) not null,
  actor_role_code varchar(100) not null,
  entity_type varchar(100) not null,
  entity_id varchar(255) not null,
  summary varchar(1000) not null,
  occurred_at timestamp with time zone not null
);
