create table if not exists documents (
  id bigint generated by default as identity primary key,
  document_type_code varchar(100) not null,
  title varchar(255) not null,
  scope_type varchar(50) not null,
  board_id bigint,
  school_id bigint,
  created_by_user_id bigint not null,
  active_version_number integer not null,
  workflow_status varchar(30) not null,
  active boolean not null default true,
  created_at timestamp with time zone not null,
  updated_at timestamp with time zone not null
);

create table if not exists document_versions (
  id bigint generated by default as identity primary key,
  document_id bigint not null,
  version_number integer not null,
  status varchar(30) not null,
  content_json varchar(20000) not null,
  change_summary varchar(500),
  created_by_user_id bigint not null,
  created_at timestamp with time zone not null,
  constraint fk_document_version_document
    foreign key (document_id) references documents(id),
  constraint uk_document_version_number
    unique (document_id, version_number)
);

insert into capabilities (code, display_name_nl, description_nl, active)
select 'EDIT_DOCUMENT', 'Document bewerken', 'Mag concepten maken en bewerken in de webeditor', true
where not exists (select 1 from capabilities where code = 'EDIT_DOCUMENT');

insert into capabilities (code, display_name_nl, description_nl, active)
select 'REVIEW_DOCUMENT', 'Document reviewen', 'Mag documentversies ter review zetten', true
where not exists (select 1 from capabilities where code = 'REVIEW_DOCUMENT');

insert into role_capability_codes (role_id, capability_code)
select r.id, 'EDIT_DOCUMENT'
from roles r
where r.code in ('PLATFORM_ADMIN', 'DIRECTEUR', 'BESTUURS_KC', 'ONDERWIJSADVISEUR')
  and not exists (
    select 1 from role_capability_codes rc
    where rc.role_id = r.id and rc.capability_code = 'EDIT_DOCUMENT'
  );

insert into role_capability_codes (role_id, capability_code)
select r.id, 'REVIEW_DOCUMENT'
from roles r
where r.code in ('PLATFORM_ADMIN', 'DIRECTEUR', 'BESTUURS_KC')
  and not exists (
    select 1 from role_capability_codes rc
    where rc.role_id = r.id and rc.capability_code = 'REVIEW_DOCUMENT'
  );

insert into role_capability_codes (role_id, capability_code)
select r.id, 'APPROVE_DOCUMENT'
from roles r
where r.code = 'PLATFORM_ADMIN'
  and not exists (
    select 1 from role_capability_codes rc
    where rc.role_id = r.id and rc.capability_code = 'APPROVE_DOCUMENT'
  );

alter table documents alter column id restart with 100;
alter table document_versions alter column id restart with 100;
