alter table documents add column if not exists summary varchar(1000);
alter table documents add column if not exists source_reference varchar(255);
alter table documents add column if not exists published_at timestamp with time zone;

create table if not exists document_user_statuses (
  id bigint generated by default as identity primary key,
  document_id bigint not null,
  user_id bigint not null,
  onboarding_status varchar(50) not null,
  last_read_at timestamp with time zone,
  updated_at timestamp with time zone not null,
  updated_by_user_id bigint not null,
  constraint fk_document_user_status_document
    foreign key (document_id) references documents(id),
  constraint uk_document_user_status_document_user
    unique (document_id, user_id)
);

alter table document_user_statuses alter column id restart with 100;
