create table if not exists document_topic_mappings (
  id bigint generated by default as identity primary key,
  document_id bigint not null,
  topic_id bigint not null,
  mapping_source varchar(100) not null,
  created_at timestamp with time zone not null,
  created_by_user_id bigint not null,
  constraint fk_document_topic_mapping_document
    foreign key (document_id) references documents(id),
  constraint fk_document_topic_mapping_topic
    foreign key (topic_id) references inspection_topics(id),
  constraint uk_document_topic_mapping_document_topic
    unique (document_id, topic_id)
);

alter table document_topic_mappings alter column id restart with 100;
