create table if not exists boards (
  id bigint generated by default as identity primary key,
  code varchar(100) not null unique,
  display_name_nl varchar(255) not null,
  active boolean not null default true
);

create table if not exists schools (
  id bigint generated by default as identity primary key,
  brin varchar(50) not null unique,
  display_name_nl varchar(255) not null,
  active boolean not null default true
);

create table if not exists board_school_relations (
  id bigint generated by default as identity primary key,
  board_id bigint not null,
  school_id bigint not null,
  relation_type varchar(100) not null,
  active boolean not null default true,
  constraint fk_board_school_relation_board
    foreign key (board_id) references boards(id),
  constraint fk_board_school_relation_school
    foreign key (school_id) references schools(id),
  constraint uk_board_school_relation
    unique (board_id, school_id, relation_type)
);

alter table boards alter column id restart with 100;
alter table schools alter column id restart with 100;
alter table board_school_relations alter column id restart with 100;
